### ISSUE TITLE
How to disable this while still using Impact Pack?

### ISSUE THREAD

**Issue by the729** [ltdrdata/ComfyUI-Impact-Subpack#10]
The readme says this package is "not deemed suitable for inclusion by default in the ComfyUI Impact Pack". However, it is installed by default.

I'm wondering how can I use the Pack without Subpack, just like what the readme means?

**Comment by ltdrdata** [comment]
I am currently working on separating it. The implementation has already been completed internally, but I am exploring ways to prevent confusion among existing users.

**Comment by ltdrdata** [comment]
Updating Impact Pack to v8 will remove this.
Now you can install subpack via ComfyUI-Manager optionally.
