### ISSUE TITLE
Ultralytics Detector provider don't see models

### ISSUE THREAD

**Issue by condr-at** [ltdrdata/ComfyUI-Impact-Subpack#13]
<img width="1533" alt="Screenshot 2024-12-15 at 15 39 05" src="https://github.com/user-attachments/assets/662e97b9-8fa7-4d7f-91fd-9d5738f6fbd3" />

**Comment by ltdrdata** [comment]
Do you use desktop version?

**Comment by condr-at** [comment]
Yes. Desktop. Hope this file is correct one.
[comfyui_8000.log](https://github.com/user-attachments/files/18140849/comfyui_8000.log)

**Comment by ltdrdata** [comment]
Is the path where your model file is saved `/Users/user/ComfyUI/models/ultralytics/bbox`?

**Comment by condr-at** [comment]
> Is the path where your model file is saved `/Users/user/ComfyUI/models/ultralytics/bbox`?

Yes.

**Comment by ltdrdata** [comment]
Update subpack to latest version and upload the log again.

**Comment by condr-at** [comment]
No luck.

[comfyui_8000.log](https://github.com/user-attachments/files/18141028/comfyui_8000.log)

**Comment by ltdrdata** [comment]
What I was trying to check is this.
```
/Applications/ComfyUI.app/Contents/Resources/ComfyUI/models/ultralytics/bbox
/Applications/ComfyUI.app/Contents/Resources/ComfyUI/models/ultralytics/segm
```

Do you use `extra_model_paths.yaml`?
In that case, you need to add `ultralytics_bbox` and `ultralytics_segm`; otherwise, it will point to a path based on the base model path.

**Comment by ak3389** [comment]
The same problem occurs on the desktop version as well. The loader is unable to load the model. No model file is displayed.

**Comment by condr-at** [comment]
> Do you use `extra_model_paths.yaml`?
I have no idea.

> you need to add `ultralytics_bbox` and `ultralytics_segm`;
Where exactly?

**Comment by ltdrdata** [comment]
> > Do you use `extra_model_paths.yaml`?
> 
> I have no idea.
> 
> > you need to add `ultralytics_bbox` and `ultralytics_segm`;
> 
> Where exactly?

Oh, aren't you using a separate configuration for `extra_model_paths.yaml`?

**Comment by ltdrdata** [comment]
> > Oh, aren't you using a separate configuration for `extra_model_paths.yaml`?
> 
> IDK. Even if I use it, it used automatically. Consider me as a total noob, sorry.

Please upload the `~/Library/Application Support/ComfyUI/extra_model_config.yaml` file.

**Comment by condr-at** [comment]
[extra_models_config.yaml.zip](https://github.com/user-attachments/files/18148300/extra_models_config.yaml.zip)

**Comment by condr-at** [comment]
Yes! Thank you! It works after adding
```
ultralytics_bbox: models/ultralytics/bbox/
ultralytics_segm: models/ultralytics/segm/
ultralytics: models/ultralytics/
```
into `extra_models_config.yaml`

Thank you so much!

PS, is it possible to update repository (ComfyUI? Node Manager?) to avoid manual adding in the future?

**Comment by ltdrdata** [comment]
It is updated.
