### ISSUE TITLE
UltralyticsDetectorProvider node not recognized after nodes update

### ISSUE THREAD

**Issue by vtsst3** [ltdrdata/ComfyUI-Impact-Subpack#15]
After updating all nodes, UltralyticsDetectorProvider node is no longer recognized. Has the name been changed? What should I do to fix this?
![image](https://github.com/user-attachments/assets/cc035430-76b0-4cb9-80db-7097c7467d09)

**Comment by ltdrdata** [comment]
Install `ComfyUI Impact Subpack`. 
Now it requires a separate installation.

**Comment by vtsst3** [comment]
Thank you for your help! I apologize for troubling you - I hadn't even checked the 'install missing node' section. Really appreciate you pointing that out.
