### ISSUE TITLE
How to get the UltralyticsDetectorProvider node?

### ISSUE THREAD

**Issue by somebush** [ltdrdata/ComfyUI-Impact-Subpack#4]
I installed `ComfyUI-Impact-Pack` and set `mmdet_skip = False`, but I can't use the `UltralyticsDetectorProvider` node.

**Comment by ltdrdata** [comment]
No. you should keep the `mmdet_skip` as `True`.

The subpack is not designed for manual installation. 
Please check if `ComfyUI-Impact-Pack/impact_subpack` exists. If it does, the installation is complete. 

However, recently there have been reports of installation failures of the Ultralytics package in specific environments, such as StabilityMatrix or MINGW, resulting in the deactivation of those nodes.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/280
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/281
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/287

If you encounter a message indicating that the `impact_subpack` exists but Ultralytics cannot be found, please manually install Ultralytics.
