### ISSUE TITLE
Still cannot use UltralyticsDetectorProvider node

### ISSUE THREAD

**Issue by lonelyman0907** [ltdrdata/ComfyUI-Impact-Subpack#6]
I have ComfyUI-Impact-Pack/impact_subpack, and also installed ultralytics manually, but still cannot use UltralyticsDetectorProvider node.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Subpack/assets/114672437/9eb8496e-700c-4af8-8e8a-47803e539c07)

**Comment by ltdrdata** [comment]
Update your ComfyUI-Manager to latest version.
It should be V1.15.


If error occurs persistently.
Show me the full startup log

**Comment by lonelyman0907** [comment]
Still not working
Here's the related log

### Loading: ComfyUI-Impact-Pack (V4.48.8)
### ComfyUI-Impact-Pack: Updating dependencies [19 -> 19]
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['C:\\Users\\Nix Lai\\Desktop\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: Check basic models
'Logger' object has no attribute 'encoding'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['C:\\Users\\Nix Lai\\Desktop\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: Check basic models
[Impact Pack] Wildcards loading done.
'Logger' object has no attribute 'encoding'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

**Comment by ltdrdata** [comment]
> Still not working
> Here's the related log
> 
> ### Loading: ComfyUI-Impact-Pack (V4.48.8)
> ### ComfyUI-Impact-Pack: Updating dependencies [19 -> 19]
> ### ComfyUI-Impact-Pack: Check dependencies
> ### ComfyUI-Impact-Pack: Updating subpack
> [Impact Pack] EXECUTE: ['C:\\Users\\Nix Lai\\Desktop\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
> req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
> 
> [notice] A new release of pip is available: 23.3.1 -> 23.3.2
> [notice] To update, run: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
> req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
> req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
> ### ComfyUI-Impact-Pack: Check basic models
> 'Logger' object has no attribute 'encoding'
> 
> !!!!!
> 
> [ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
>         https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md
> 
> !!!!!
> 
> ### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
> ### ComfyUI-Impact-Pack: Check dependencies
> ### ComfyUI-Impact-Pack: Updating subpack
> [Impact Pack] EXECUTE: ['C:\\Users\\Nix Lai\\Desktop\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
> req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
> 
> [notice] A new release of pip is available: 23.3.1 -> 23.3.2
> [notice] To update, run: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
> req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
> req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
> ### ComfyUI-Impact-Pack: Check basic models
> [Impact Pack] Wildcards loading done.
> 'Logger' object has no attribute 'encoding'
> 
> !!!!!
> 
> [ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
>         https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md
> 
> !!!!!
> 
> ### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack
> 
>   The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
>   Recommended to delete the path and restart ComfyUI.
>   If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

I am saying **full log**. Because your are missing the point.

**Comment by lonelyman0907** [comment]
My apology for the misunderstanding,
Here's the full log

C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-12-22 19:55:36.132696

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main
   0.1 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate

Total VRAM 23028 MB, total RAM 65277 MB
2023-12-22 19:55:43.099913: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints C:\Users\Nix Lai\Desktop\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\Users\Nix Lai\Desktop\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\Users\Nix Lai\Desktop\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\Users\Nix Lai\Desktop\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\Users\Nix Lai\Desktop\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\Users\Nix Lai\Desktop\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\Users\Nix Lai\Desktop\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\Users\Nix Lai\Desktop\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\Users\Nix Lai\Desktop\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\Users\Nix Lai\Desktop\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet C:\Users\Nix Lai\Desktop\stable-diffusion-webui\models/ControlNet
### Loading: ComfyUI-Impact-Pack (V4.48.8)
'Logger' object has no attribute 'encoding'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['C:\\Users\\Nix Lai\\Desktop\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: Check basic models
'Logger' object has no attribute 'encoding'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 443, in <module>
    import impact.subpack_nodes
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 15, in <module>
    raise e
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 11, in <module>
    from ultralytics import YOLO
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 265, in <module>
    LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE)  # define globally (used in train.py, val.py, predict.py, etc.)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 233, in set_logging
    if WINDOWS and sys.stdout.encoding != 'utf-8':
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'encoding'
---------------------------------

Traceback (most recent call last):
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Nix Lai\\Desktop\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Subpack\\__init__.py'

Cannot import C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\Nix Lai\\Desktop\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Subpack\\__init__.py'
### Loading: ComfyUI-Inspire-Pack (V0.52)
### Loading: ComfyUI-Manager (V1.0.1)
### ComfyUI Revision: 1847 [6781b181] | Released on '2023-12-21'
--------------
Mixlab Nodes: Loaded
--------------
Portrait Maker ============== ### ComfyUI-Portrait-Maker: Check dependencies
Portrait Maker ============== C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker\requirements.txt
Portrait Maker ============== aliyun-python-sdk-core-v3==2.13.10


[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Portrait Maker ============== opencv-python

Portrait Maker ============== tensorflow-cpu

Portrait Maker ============== tensorflow

Portrait Maker ============== onnx

Portrait Maker ============== onnxruntime

Portrait Maker ============== modelscope

Portrait Maker ============== scikit-image

Portrait Maker ============== matplotlib

Portrait Maker ============== insightface

Portrait Maker ============== diffusers==0.18.2

Portrait Maker ============== sentencepiece
2023-12-22 19:56:09,536 - modelscope - INFO - PyTorch version 2.1.0+cu121 Found.
2023-12-22 19:56:09,537 - modelscope - INFO - TensorFlow version 2.15.0 Found.
2023-12-22 19:56:09,537 - modelscope - INFO - Loading ast index from C:\Users\Nix Lai\.cache\modelscope\ast_indexer
2023-12-22 19:56:09,699 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 f266260f8e8b55c09e66b0d5798ed330 and a total number of 946 components indexed
Traceback (most recent call last):
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker\__init__.py", line 9, in <module>
    from portrait.nodes import *
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker\portrait\nodes.py", line 7, in <module>
    from .model_holder import *
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker\portrait\model_holder.py", line 1, in <module>
    from modelscope.pipelines import pipeline
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
    from .base import Pipeline
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\modelscope\pipelines\base.py", line 16, in <module>
    from modelscope.msdatasets import MsDataset
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\modelscope\msdatasets\__init__.py", line 2, in <module>
    from .ms_dataset import MsDataset
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 9, in <module>
    from datasets import Dataset, DatasetDict, IterableDataset, IterableDatasetDict
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\datasets\__init__.py", line 22, in <module>
    from .arrow_dataset import Dataset
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\datasets\arrow_dataset.py", line 60, in <module>
    import pyarrow as pa
ModuleNotFoundError: No module named 'pyarrow'

Cannot import C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker module for custom nodes: No module named 'pyarrow'
[SD Prompt Reader] Node version: 1.2.0
[SD Prompt Reader] Core version: 1.3.4.post1
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
Total VRAM 23028 MB, total RAM 65277 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.0+cu121
Traceback (most recent call last):
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 19, in <module>
    from basicsr.utils.registry import ARCH_REGISTRY
ModuleNotFoundError: No module named 'basicsr'

Cannot import C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'basicsr'
### Loading: Workspace Manager (V1.0.0)
Comfyroll Custom Nodes: Loaded
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
FizzleDorf Custom Nodes: Loaded
[tinyterraNodes] Loaded
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\web\extensions\failfast-comfyui-extensions
C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\AutoUpdate.json

[rgthree] Loaded 20 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 198 nodes successfully.

        "Art is the freedom to create, explore, and inspire." - Unknown


Import times for custom nodes:
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ResizeAspectratio.py
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\rembg-comfyui-node
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\StableZero123-comfyui
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds (IMPORT FAILED): C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg_custom_core
   0.0 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node
   0.1 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\failfast-comfyui-extensions
   0.1 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\CharacterFaceSwap
   0.2 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate
   0.2 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.3 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main
   0.6 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.8 seconds (IMPORT FAILED): C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.9 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT
   1.2 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   1.3 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   1.4 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.5 seconds (IMPORT FAILED): C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker
  13.2 seconds: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

https_key OK:  C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\certificate.crt C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\private.key
Starting server

To see the GUI go to: http://127.0.0.1:8188
To see the GUI go to: https://127.0.0.1:8189
FETCH DATA from: C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main\extension-node-map.json
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready
data_path:  C:\Users\Nix Lai\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\data

**Comment by ltdrdata** [comment]
- [ ]
